// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('D:/Project/chengpeiquan.com/src/components/blog/Article.vue')['default']
    BackToTop: typeof import('E:/Project/chengpeiquan.com/src/components/BackToTop.vue')['default']
    BlogArticle: typeof import('E:/Project/chengpeiquan.com/src/components/blog/Article.vue')['default']
    BlogDetail: typeof import('D:/Project/chengpeiquan.com/src/components/blog/Detail.vue')['default']
    BlogList: typeof import('E:/Project/chengpeiquan.com/src/components/blog/List.vue')['default']
    BlogPage: typeof import('D:/Project/chengpeiquan.com/src/components/blog/Page.vue')['default']
    BlogPagination: typeof import('D:/Project/chengpeiquan.com/src/components/blog/Pagination.vue')['default']
    BlogSidebar: typeof import('E:/Project/chengpeiquan.com/src/components/blog/Sidebar.vue')['default']
    CategoryTabs: typeof import('E:/Project/chengpeiquan.com/src/components/CategoryTabs.vue')['default']
    ChildrenList: typeof import('E:/Project/chengpeiquan.com/src/components/ChildrenList.vue')['default']
    CookbookArticle: typeof import('E:/Project/chengpeiquan.com/src/components/cookbook/Article.vue')['default']
    CookbookList: typeof import('E:/Project/chengpeiquan.com/src/components/cookbook/List.vue')['default']
    CookbookSidebar: typeof import('E:/Project/chengpeiquan.com/src/components/cookbook/Sidebar.vue')['default']
    CookingList: typeof import('D:/Project/chengpeiquan.com/src/components/cooking/List.vue')['default']
    Detail: typeof import('E:/Project/chengpeiquan.com/src/components/Detail.vue')['default']
    Footer: typeof import('E:/Project/chengpeiquan.com/src/components/Footer.vue')['default']
    FriendlyLinks: typeof import('E:/Project/chengpeiquan.com/src/components/FriendlyLinks.vue')['default']
    GoogleAdsense: typeof import('E:/Project/chengpeiquan.com/src/components/GoogleAdsense.vue')['default']
    Header: typeof import('E:/Project/chengpeiquan.com/src/components/Header.vue')['default']
    IcTwotoneArrowBackIos: typeof import('virtual:vite-icons/ic/twotone-arrow-back-ios')['default']
    List: typeof import('D:/Project/chengpeiquan.com/src/components/blog/List.vue')['default']
    Page: typeof import('E:/Project/chengpeiquan.com/src/components/Page.vue')['default']
    Pagination: typeof import('E:/Project/chengpeiquan.com/src/components/Pagination.vue')['default']
    'Ri:listCheck2': typeof import('virtual:vite-icons/ri/list-check2')['default']
    RiCloseFill: typeof import('virtual:vite-icons/ri/close-fill')['default']
    RiEnglishInput: typeof import('virtual:vite-icons/ri/english-input')['default']
    RiFireFill: typeof import('virtual:vite-icons/ri/fire-fill')['default']
    RiGithubFill: typeof import('virtual:vite-icons/ri/github-fill')['default']
    RiMenuFill: typeof import('virtual:vite-icons/ri/menu-fill')['default']
    RiMoonLine: typeof import('virtual:vite-icons/ri/moon-line')['default']
    RiRssFill: typeof import('virtual:vite-icons/ri/rss-fill')['default']
    RiStarLine: typeof import('virtual:vite-icons/ri/star-line')['default']
    RiSunLine: typeof import('virtual:vite-icons/ri/sun-line')['default']
    RiTwitterFill: typeof import('virtual:vite-icons/ri/twitter-fill')['default']
    RiZhihuFill: typeof import('virtual:vite-icons/ri/zhihu-fill')['default']
    Sidebar: typeof import('D:/Project/chengpeiquan.com/src/components/blog/Sidebar.vue')['default']
    TOC: typeof import('E:/Project/chengpeiquan.com/src/components/TOC.vue')['default']
    ToggleLang: typeof import('E:/Project/chengpeiquan.com/src/components/ToggleLang.vue')['default']
    ToggleTheme: typeof import('E:/Project/chengpeiquan.com/src/components/ToggleTheme.vue')['default']
    UilLetterChineseA: typeof import('virtual:vite-icons/uil/letter-chinese-a')['default']
  }
}

export { }
