name: github-ci

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: npm install and build
    #   run: |
    #     npm install
    #     npm run build
    # find yarn cache
    - name: Get yarn cache path
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    # update cache
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    # generate artifacts
    - run: yarn install
    - run: yarn build
    - name: github-ci
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}